name: Build LNReader Debug APK

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'         # Optional: Remove if you don't want tag-based builds

env:
  VERSION_NAME: "2.0.0"  # Hardcoded version
  ABI_FILTER: "arm64-v8a"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Debug APK
        run: |
          cd android/
          ./gradlew assembleArm64Debug \
            -PversionName=$VERSION_NAME \
            -PabiFilters=$ABI_FILTER \
            -PdisableOtherAbis=true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v$VERSION_NAME"  # Creates v2.0.0 tag
          name: "LNReader $VERSION_NAME (Debug)"
          body: "Unsigned debug APK (arm64-v8a)"
          files: |
            android/app/build/outputs/apk/arm64/debug/app-arm64-debug.apk
          draft: false
          prerelease: true  # Mark as pre-release since it's unsigned
